### ISSUE TITLE
deadlock on sync and message processor threads

### ISSUE THREAD

**Issue by yuriy-glotanov** [interference-project/interference#2]
**Describe the bug**
Deadlock on sync and message processor threads found.

**To Reproduce**
Start stress testing inserts/updates on 2-3 nodes.

**Additional context**
Deadlock happens when sync thread start and message processor is process of sync frame event. There is small sad bug in sync frame event processing, when trying LLT.acquire after lock datafile.
Need accurate reordering of this case.

**Comment by interference-project** [comment]
fixed
